[project]
name = "ep-ai"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "jupyter>=1.1.1",
    "sniffio>=1.3.1",
    "zai-sdk>=0.2.0",
]
